### PR TITLE
Upgrade Ruby to `2.7.4` and gem dependencies

### PR DESCRIPTION
**Pull request by waldofouche**
Updates Ruby  and gem dependencies:

- Ruby from 2.6.6 to 2.7.4
- All other gem dependencies to latest versions
- Fix rubocop violations

This is part of ausaccessfed/stockpile#87

### CODE REVIEW

**Comment by rianniello** [comment]
What's the reasoning for staying at ruby `2.6.6` ?

**Comment by waldofouche** [comment]
The previous Patches kept it at `2.6.6` https://github.com/ausaccessfed/rapidconnect/pull/94 when the other's were updated. I can upgrade it to `2.7.4` however and see if there are no major issues.

**Comment by rianniello** [comment]
Ok, looks like I must had some reasons, but didn't document it that well in my PR. My bad. Worth having a quick go to see if you can upgrade it, as I believe RapidConnect will be living at 2022-03-31 :)

**Comment by waldofouche** [comment]
Looks like the rollout was successful to test, will keep watch for a week or so to make sure nothing breaks

**Pull request merged**
